spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/makeat
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

kakao:
  client_id: 0658266bd27dd7c683f32dc7aecb3faf
  redirect_url: http://localhost:8080/user/kakao

logging:
  level:
    org.hibernate.sql: debug

